os: linux

git:
  submodules: false
  
language: python

dist: xenial

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pyflakes
  - pip install coverage codacy-coverage

script:
  - find . | grep -E "\.py$" | xargs python -m compileall
  - find . | grep -E "\.py$" | xargs pyflakes

after_script:
  - coverage xml
  - python-codacy-coverage -r coverage.xml

cache: pip

notifications:
  email: false
